# Generated by Django 4.2.7 on 2025-11-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='battery_capacity_kwh',
            field=models.DecimalField(decimal_places=2, default=1320.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='farm',
            name='system_size_kw',
            field=models.DecimalField(decimal_places=2, default=130.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='battery_kwh',
            field=models.DecimalField(decimal_places=2, default=924.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='pv_output_kw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
