# Generated by Django 4.2.7 on 2025-11-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_update_system_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatus',
            name='current_load_kw',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='current_soil_moisture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='irrigation_priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('normal', 'Normal'), ('optional', 'Optional')], default='optional', max_length=20),
        ),
    ]
